services: 
  python:
    build: ./docker/python
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker 
    volumes:
      - ./docker/database:/var/lib/mysql
      - ./docker/database-init:/docker-entrypoint-initb.d
    ports:
      - "3306:3306"

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1456:1080"
      - "1425:1025"

